# .github/workflows/update-lists.yml
name: Update Phishing Lists

on:
  schedule:
    - cron: '0 4 * * *'  # 毎日4時UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Process lists
        run: node scripts/process-lists.js
        
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lists/
          git diff --staged --quiet || git commit -m "Update phishing lists - $(date -u)"
          git push
